# Generated by Django 4.2.3 on 2024-05-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('billing_address', models.TextField()),
                ('order_history', models.TextField()),
                ('favourite_list', models.TextField()),
                ('feedback', models.TextField()),
            ],
        ),
    ]
