# Generated by Django 4.2.3 on 2024-05-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='billing_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='favourite_list',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='order_history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
