# Generated by Django 4.2.3 on 2024-05-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='favourite_list',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='order_history',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
