# Generated by Django 4.2.3 on 2024-05-17 15:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_favourite_list_alter_users_order_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='favourite_list',
            field=models.JSONField(blank=True, default=users.models.default_empty_list),
        ),
        migrations.AlterField(
            model_name='users',
            name='order_history',
            field=models.JSONField(blank=True, default=users.models.default_empty_list),
        ),
    ]
