# Generated by Django 4.2.3 on 2024-05-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_favourite_list_alter_users_order_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.users')),
            ],
        ),
    ]
