# Generated by Django 4.2.3 on 2024-05-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_ser_feedback_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_text',
            new_name='feedback',
        ),
    ]
