# Generated by Django 4.2.3 on 2024-05-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_users_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='billing_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
