# Generated by Django 4.2.3 on 2024-05-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_users_billing_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
