# Generated by Django 4.2.3 on 2024-05-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='billing_address',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
