# Generated by Django 4.2.3 on 2024-05-19 10:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_users_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='billing_address',
            field=models.JSONField(blank=True, default=users.models.default_empty_list),
        ),
    ]
