# Generated by Django 4.2.3 on 2024-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_users_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='No name', max_length=25),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(default='+910987654321', max_length=17, unique=True),
        ),
    ]
